### ISSUE TITLE
Tuple error using dace.map with Python 3.10

### ISSUE THREAD

**Issue by JamieJQuinn** [spcl/dace#904]
**Describe the bug**
`to_sdfg()` fails when using `dace.map` with Python 3.10, producing the error:

```
AttributeError: 'Tuple' object has no attribute 'value'
```

**To Reproduce**
1. Run this minimal example with dace 0.10.0 and Python 3.10:

```
import dace

N = dace.symbol('N')

@dace.program
def map_fail(A: dace.float64[N,N], B: dace.float64[N,N]):
    for i, j in dace.map[0:N, 0:N]:
        A[i,j] = 2.0*B[i,j]

map_fail.to_sdfg()
```

**Expected behavior**
Expect graph to compile

**Screenshots**
No screenshot but full traceback:
```
Traceback (most recent call last):
  File "/home/jamie/prog/dace_bugs/3.10_bug.py", line 10, in <module>
    map_fail.to_sdfg()
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/parser.py", line 239, in to_sdfg
    return parse_from_function(self, *args, strict=strict)
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/parser.py", line 109, in parse_from_function
    sdfg = function.generate_pdp(*compilation_args)
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/parser.py", line 334, in generate_pdp
    return newast.parse_dace_program(dace_func, argtypes, global_vars,
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 175, in parse_dace_program
    sdfg, _, _ = pv.parse_program(src_ast.body[0])
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 1034, in parse_program
    self.visit_TopLevel(stmt)
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/astutils.py", line 298, in visit_TopLevel
    self.visit(node)
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 1014, in visit
    return super().visit(node)
  File "/usr/lib/python3.10/ast.py", line 410, in visit
    return visitor(node)
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 1917, in visit_For
    iterator, ranges = self._parse_for_iterator(node.iter)
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 1499, in _parse_for_iterator
    ranges.append(self._parse_index_as_range(node.slice))
  File "/home/jamie/prog/dace_bugs/.venv_3.10/lib/python3.10/site-packages/dace/frontend/python/newast.py", line 1448, in _parse_index_as_range
    val = self._parse_value(node.value)
AttributeError: 'Tuple' object has no attribute 'value'
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 95

**Comment by tbennun** [comment]
@JamieJQuinn which dace version are you using? 

I'm asking because we are releasing a new version of dace, and our CI has been running with Python 3.10 for the past two weeks or so.

**Comment by tbennun** [comment]
Version released, dace 0.11.4 should support Python 3.10

**Comment by JamieJQuinn** [comment]
Yep, my mistake. Not sure why my pip installed version 0.10... Works fine with 0.11.4!
