### ISSUE TITLE
Dace does not work with Python 3.6

### ISSUE THREAD

**Issue by JamieJQuinn** [spcl/dace#896]
**Describe the bug**

Although the dace readme states python 3.6+ should work, running dace with python 3.6 will throw an `ImportError`:

```
  File "[...]/dace/frontend/python/common.py", line 5, in <module>
    from typing import (Any, Callable, Dict, List, Optional, OrderedDict, Sequence,
ImportError: cannot import name 'OrderedDict'
```

`OrderedDict` was actually introduced in Python 3.7.2 (see [docs](https://docs.python.org/3/library/typing.html#typing.OrderedDict)) so 3.7.2 should probably be required as the minimum version.

**To Reproduce**
1. Run any dace sample using python 3.6 (e.g. `samples/simple/axpy.py`)

**Expected behavior**
dace should run the sample without error

**Desktop (please complete the following information):**
 - Linux
 - Firefox
 - Version 95

**Comment by tbennun** [comment]
Thanks for reporting! Indeed the OrderedDict type hint was introduced later, but is not necessary for the functionality of dace.

I made a PR (#897) which passes locally with Python 3.6. I'll merge it as soon as tests pass and you can check it out as well.

**Comment by tbennun** [comment]
@JamieJQuinn please let us know if this works for you.

**Comment by JamieJQuinn** [comment]
Fixed for me, cheers!
